### ISSUE TITLE
no outputs with log after upgrade to wasmbus-rpc 0.10

### ISSUE THREAD

**Issue by Finfalter** [wasmCloud/weld#116]
@stevelr @thomastaylor312 

After having upgraded to `wasmbus-rpc = "0.10"` I do not see any log outputs (used crate is `log = "0.4"`).
Also, following instructions for [changing log level](https://wasmcloud.dev/app-dev/debugging/host/), the following
```
Logger.configure(level: :debug)
``` 
fails with
```
iex(wasmcloud_host@127.0.0.1)1> Logger.configure(level: :debug)
** (MatchError) no match of right hand side value: {:error, {:not_found, Logger}}
    (logger 1.12.3) lib/logger.ex:588: Logger.configure/1
```
P.s. crate `tracing` produces log outputs.

**Comment by stevelr** [comment]
wasmbus-rpc (the layer used underneath all rust capability providers) uses tracing for all logging. When writing a capability provider using wasmbus-rpc, you have a couple options for logging:

- use the `tracing` crate at all layers. You can pretty much replace the `log` crate with `tracing` crate for all the macros (`debug!`, etc.), and it has the advantage that trace events are connected to the spans created by the host and wasmbus-rpc. Inside your provider's `main()`, you call either `provider_run` or `provider_main` (which calls `provider_run`) to initialize wasmbus_rpc. Inside `provider_run` tracing is  initialized. 
- (note: if you need to log anything to stdout or stderr _before_ calling `provider_main` or `provider_run`, use println! or eprintln! because tracing hasn't been initialized yet).


- If you want to use the `log` crate, or you have a dependency on some other crate that uses the logging crate, add `tracing-log` to your dependencies in Cargo.toml, and initialize logging inside your provider's main function with 
```
tracing_log::LogTracer::init()?;
```
When `wasmbus-rpc` initializes tracing, it will intercept all calls to the log provider send them to stdout with the tracing logs from wasmbus-rpc.

- Whether you choose to use `log` or `tracing` for logging within your provider, logs always go to stdout. If the wasmbus-rpc feature flag `"otel"` is enabled, trace data is also sent to an OTEL collector. The otel collector endpoint is configured with the environment variables `OTEL_TRACES_EXPORTER` (default value: "otlp") and `OTEL_EXPORTER_OTLP_ENDPOINT` (default value: http://localhost:55681)

@Finfalter does that make it work for you?

**Comment by Finfalter** [comment]
@stevelr absolutely, it works!
